### ISSUE TITLE
jolt: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CreeperGamerGitHub** [vloddot/jolt#27]
Not Crostini compatible unless i need to install webGL.

**Comment by vloddot** [comment]
You mean it doesn't have the OpenGL library installed in the AppImage?

**Comment by CreeperGamerGitHub** [comment]
> You mean it doesn't have the OpenGL library installed in the AppImage? Also, what exactly is crostini? Is it a ChromeOS thing?

Vlod, what do think i was using? I said i had a chromebook.

**Comment by CreeperGamerGitHub** [comment]
> I found out what [Crostini](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/containers_and_vms.md) is.
> 
> Umm... might be sort of a problem with your machine. I think OpenGL should be on all systems, but this is a VM after all and it might not have everything.
> 
> I will close this for now, if you have a good reason to re-open, then please mention it.

Oh okay! Thanks vlod!
