### ISSUE TITLE
Incredibly Slow Requests for Messages

### ISSUE THREAD

**Issue by vloddot** [vloddot/jolt#8]
All in the title. Takes around 30 seconds to do requests. (possibly different on some machines)

**Comment by toastxc** [comment]
the default timeout for reywen-http is 10 seconds, perhaps this could be modified

**Comment by vloddot** [comment]
Issue is fixed in the latest release. Fix is using `RwLock` which blocks for write requests only (requests not included) instead of using something like `Mutex` which blocks for both read and write. All thanks to @toastxc in #26.
